# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  pitchlineapi:
    image: pitchlineapi
    build:
      context: .
      dockerfile: match-engine/PitchLine.API/Dockerfile
    ports:
      - 5050:5050
